### ISSUE TITLE
KeyError: 'r0'

### ISSUE THREAD

**Issue by yaghmr** [ucsb-seclab/karonte#6]
I ran the example, and I get this error:

```
$ python tool/karonte.py config/NETGEAR/r_7800.json 
Traceback (most recent call last):
  File "tool/karonte.py", line 6, in <module>
    from binary_dependency_graph import BinaryDependencyGraph
  File "/karonte-master/tool/binary_dependency_graph/__init__.py", line 1, in <module>
    from binary_dependency_graph import *
  File "/karonte-master/tool/binary_dependency_graph/binary_dependency_graph.py", line 7, in <module>
    from utils import *
  File "/karonte-master/tool/binary_dependency_graph/utils.py", line 14, in <module>
    from taint_analysis import coretaint, summary_functions
  File "/karonte-master/tool/taint_analysis/coretaint.py", line 7, in <module>
    from utils import *
  File "/karonte-master/tool/taint_analysis/utils.py", line 5, in <module>
    archinfo.ArchARMEL.registers['r0'][0],
KeyError: 'r0'
```

**Comment by badnack** [comment]
Are you running the code inside the karonte container, or directly on your system?

**Comment by yaghmr** [comment]
Directly on my system: Linux Ubuntu 18.04, Python 2.7

**Comment by badnack** [comment]
Angr has changed a lot since karonte, I d suggest you to use our container. You can find the link in the readme.

**Comment by yaghmr** [comment]
I see. What version of Angr is needed to karonte? I tried the version 7.8.9.26 and 7.8.8.1 but I get the same error.
